import { ThemeProvider } from '@mui/material/styles';
import theme from '../components/theme';
import '../app/globals.css';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(props) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeProvider theme={theme}>
                    {props.children}
                </ThemeProvider>
            </body>
        </html>
    );
}